repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
      - id: flake8
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml,
      - id: check-json,
      - id: pretty-format-json

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: {{cookiecutter.lib_name}}_app{{ cookiecutter.python_version}}