name: osmgt
channels:
  - conda-forge
  - anaconda
  - amauryval
  - defaults
dependencies:
  - python=3.9
  - geopandas>=0.10.2
  - gdf2bokeh>=2.3.1
  - numpy>=1.18.1
  - geojson>=2.5.0
  - graph-tool>=2.33
  - cairo>=1.16.0
  - scipy>=1.5.0
  - pytest
  - pytest-cov
  - jupyterlab
  - numba>=0.48.0
  - requests-futures>=1.0.0
  - more-itertools>=8.12.0
  - black