name: osmgt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - geopandas
  - bokeh
  - pytest
  - Shapely
  - requests
  - pandas
  - GDAL
  - numpy
  - pyproj
  - geojson
  - python-dateutil
  - jupyter
  - graph-tool
  - cairo