name: osmgt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - geopandas=0.8.0
  - bokeh
  - Shapely
  - requests
  - pandas
  - GDAL
  - numpy
  - pyproj
  - geojson
  - python-dateutil
  - graph-tool
  - cairo
  - scipy
  - pytest
  - pytest-cov
  - jupyter
  - ujson
  - pygeos=0.7.1