{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}

    {% for dep in data.get('install_requires') %}
    - {{ dep.lower() }}
    {% endfor %}

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: {{ data.get('license') }}
  summary: {{ data.get('description') }}
  license_file: LICENSE
