
# POIs overpass query
poi_query = 'node["amenity"]({geo_filter});node[shop]({geo_filter});'

# network overpass queries
network_queries = {
    "vehicle": 'way["highway"~"^('
                'motorway|'
                'trunk|'
                'primary|'
                'secondary|'
                'tertiary|'
                'unclassified|'
                'residential|'
                'pedestrian|'
                'motorway_link|'
                'trunk_link|'
                'primary_link|'
                'secondary_link|'
                'tertiary_link|'
                'living_street|'
                'service|'
                'track|'
                'bus_guideway|'
                'escape|'
                'raceway|'
                'road|'
                'bridleway|'
                'corridor|'
                'path'
                ')$"]["area"!~"."]({geo_filter});',
    "pedestrian": 'way["highway"~"^('
                  'motorway|'
                  'trunk|'
                  'primary|'
                  'secondary|'
                  'tertiary|'
                  'unclassified|'
                  'residential|'
                  'pedestrian|'
                  'motorway_link|'
                  'trunk_link|'
                  'primary_link|'
                  'secondary_link|'
                  'tertiary_link|'
                  'living_street|'
                  'service|'
                  'track|'
                  'bus_guideway|'
                  'escape|'
                  'raceway|'
                  'road|'
                  'footway|'
                  'bridleway|'
                  'steps|'
                  'corridor|'
                  'path'
                  ')$"]["area"!~"."]({geo_filter});'
}
