name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Launch Dockerfile & tests
      uses: ./
      run: |
        python -m pytest tests
        python -m pytest --cov=osmgt tests/ --doctest-modules

