name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update -f ./test/requirements.yml
    - name: Prove that Pytest is installed
      uses: ./
      with:
        args: python -m pytest tests





on: [push]

jobs:
  build-and-run:
    steps:
    - uses: actions/checkout@v1
    - name: Update Conda environment with "requirements.yml"
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update -f ./environment.yml
    - name: Run "pytest" with the Conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: pytest
