name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Launch Dockerfile
      uses: ./
    - name: Run tests with Pytest
      run: python -m pytest tests
    - name: Run tests Coverage
      run: python -m pytest --cov=osmgt tests/ --doctest-modules

