name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Update Conda environment
      uses: matthewrmshin/conda-action@v1
      with:
        args: conda env update -f ./environment.yml
    - name: Run tests with Pytest
      uses: ./
      with:
        args: python -m pytest tests
